# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TileSelect_frame1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 710)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_PendingPath = QtWidgets.QLabel(self.centralwidget)
        self.label_PendingPath.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_PendingPath.setFont(font)
        self.label_PendingPath.setObjectName("label_PendingPath")
        self.lineEdit_PendingPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PendingPath.setGeometry(QtCore.QRect(140, 20, 451, 20))
        self.lineEdit_PendingPath.setObjectName("lineEdit_PendingPath")
        self.toolButton_PendingPath = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_PendingPath.setGeometry(QtCore.QRect(610, 20, 31, 21))
        self.toolButton_PendingPath.setObjectName("toolButton_PendingPath")
        self.label_TilePath = QtWidgets.QLabel(self.centralwidget)
        self.label_TilePath.setGeometry(QtCore.QRect(20, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_TilePath.setFont(font)
        self.label_TilePath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_TilePath.setObjectName("label_TilePath")
        self.lineEdit_TilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_TilePath.setGeometry(QtCore.QRect(140, 60, 451, 20))
        self.lineEdit_TilePath.setObjectName("lineEdit_TilePath")
        self.toolButton_TilePath = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_TilePath.setGeometry(QtCore.QRect(610, 60, 31, 21))
        self.toolButton_TilePath.setObjectName("toolButton_TilePath")
        self.label_TileMode = QtWidgets.QLabel(self.centralwidget)
        self.label_TileMode.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label_TileMode.setFont(font)
        self.label_TileMode.setObjectName("label_TileMode")
        self.comboBox_TileMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_TileMode.setEnabled(True)
        self.comboBox_TileMode.setGeometry(QtCore.QRect(140, 100, 151, 22))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.comboBox_TileMode.setFont(font)
        self.comboBox_TileMode.setEditable(False)
        self.comboBox_TileMode.setModelColumn(0)
        self.comboBox_TileMode.setObjectName("comboBox_TileMode")
        self.comboBox_TileMode.addItem("")
        self.comboBox_TileMode.addItem("")
        self.pushButton_TileMove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TileMove.setGeometry(QtCore.QRect(540, 140, 100, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.pushButton_TileMove.setFont(font)
        self.pushButton_TileMove.setObjectName("pushButton_TileMove")
        self.pushButton_Import = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Import.setGeometry(QtCore.QRect(480, 140, 41, 21))
        self.pushButton_Import.setObjectName("pushButton_Import")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 179, 621, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setMaximumSize(QtCore.QSize(0, 10))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ContextCapture：Tile處理"))
        self.label_PendingPath.setText(_translate("MainWindow", "Pending資料夾路徑："))
        self.toolButton_PendingPath.setText(_translate("MainWindow", "..."))
        self.label_TilePath.setText(_translate("MainWindow", "Tile文字檔路徑："))
        self.toolButton_TilePath.setText(_translate("MainWindow", "..."))
        self.label_TileMode.setText(_translate("MainWindow", "Tile Mode："))
        self.comboBox_TileMode.setItemText(0, _translate("MainWindow", "Regular planar grid"))
        self.comboBox_TileMode.setItemText(1, _translate("MainWindow", "Adaptive tiling"))
        self.pushButton_TileMove.setText(_translate("MainWindow", "整理Tile資料夾"))
        self.pushButton_Import.setText(_translate("MainWindow", "匯入"))
        self.label.setText(_translate("MainWindow", "小提示：匯入資料夾路徑"))

